---
apiVersion: v1
kind: Secret
metadata:
  name: rhda-backend-secret
  labels:
    app: rhda-backend
type: Opaque
stringData:
  rhtpa.client.id: {{ .Values.oidc.clientId | quote }}
  rhtpa.client.secret: {{ .Values.oidc.clientSecret | quote }}
  rhtpa.auth.server.url: {{ .Values.oidc.issuerUrl | quote }}
