---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhda-backend-postgresql
  labels:
    app: rhda-backend-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhda-backend-postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rhda-backend-postgresql
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: rhda-backend-postgresql
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rhda-backend-postgresql
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: rhda-backend-postgresql
                  key: database-name
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 100m
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - --live
            initialDelaySeconds: 120
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: rhda-backend-postgresql
