---
apiVersion: v1
kind: Service
metadata:
  name: rhda-backend-postgresql
  labels:
    app: rhda-backend-postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: rhda-backend-postgresql
