---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhda-backend-postgresql
  labels:
    app: rhda-backend-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
