---
apiVersion: v1
kind: Secret
metadata:
  name: rhda-backend-postgresql
  labels:
    app: rhda-backend-postgresql
type: Opaque
stringData:
  database-name: {{ .Values.postgresql.database | quote }}
  database-user: {{ .Values.postgresql.username | quote }}
  database-password: {{ .Values.postgresql.password | quote }}
