---
apiVersion: v1
kind: Service
metadata:
  name: rhda-backend-redis
  labels:
    app: rhda-backend-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: rhda-backend-redis
