{{- if .Values.tpaRouteHost }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tpa-short-url
  labels:
    app: tpa
spec:
  host: {{ .Values.tpaRouteHost }}
  to:
    kind: Service
    name: server
  port:
    targetPort: endpoint
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
