---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tpa-db-monitor
  labels:
    app: tpa-db-monitor
spec:
  {{- if .Values.routeHost }}
  host: {{ .Values.routeHost }}
  {{- end }}
  to:
    kind: Service
    name: tpa-db-monitor
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
