{{- if .Values.createInstance }}
---
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: {{ .Values.namespace }}
spec:
  devEnvironments:
    defaultEditor: che-incubator/che-code/latest
    defaultNamespace:
      autoProvision: true
    env:
      - name: RHDA_BACKEND_URL
        value: "https://rhda.{{ .Values.deployer.domain }}"
  components:
    cheServer:
      debug: false
    pluginRegistry:
      openVSXURL: "https://open-vsx.org"
{{- end }}
