{{- if .Values.userinfoNamespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devspaces-userinfo
  namespace: {{ .Values.userinfoNamespace }}
  labels:
    demo.redhat.com/userinfo: ""
data:
  order: "4"
  demo_title: "DevSpaces (VS Code + RHDA)"
  {{- if .Values.factoryRepoBranch }}
  demo_url: "https://devspaces.{{ .Values.deployer.domain }}#{{ .Values.factoryRepoUrl | trimSuffix ".git" }}/tree/{{ .Values.factoryRepoBranch }}"
  {{- else }}
  demo_url: "https://devspaces.{{ .Values.deployer.domain }}#{{ .Values.factoryRepoUrl }}"
  {{- end }}
  access_instructions: "Click the link above to open the TPA demo repo in VS Code with the RHDA plugin. Open any pom.xml to trigger a vulnerability scan."
  label_1: "DevSpaces Dashboard"
  content_1: "Manage your workspaces here:"
  content_url_1: "https://devspaces.{{ .Values.deployer.domain }}"
{{- end }}
