{{- if .Values.createInstance }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devspaces-workspace-env
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/mount-as: env
    che.eclipse.org/mount-to: ws
data:
  RHDA_BACKEND_URL: "https://rhda.{{ .Values.deployer.domain }}"
{{- end }}
