---
apiVersion: v1
kind: Secret
metadata:
  name: tpa-postgresql-credentials
  labels:
    app: tpa-postgresql
type: Opaque
stringData:
  db.host: {{ .Values.credentials.dbHost | quote }}
  db.name: {{ .Values.credentials.dbName | quote }}
  db.user: {{ .Values.credentials.dbUser | quote }}
  db.password: {{ .Values.credentials.dbPassword | quote }}
  db.admin: {{ .Values.credentials.dbAdmin | quote }}
  db.adminpassword: {{ .Values.credentials.dbAdminPassword | quote }}
  db.port: {{ .Values.credentials.dbPort | quote }}
