---
apiVersion: v1
kind: Service
metadata:
  name: tpa-postgresql
  labels:
    app: tpa-postgresql
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: tpa-postgresql
  type: ClusterIP
