{{- if .Values.dbMonitor.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: tpa-db-monitor
  labels:
    app: tpa-db-monitor
spec:
  selector:
    app: tpa-db-monitor
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
{{- end }}
